export const SOCKET_EVENTS = {
  ONLINE_USERS: 'online-users',
  RECEIVE_MESSAGE: 'receive-message',
  MEDIA_PROCESSING_UPDATE: 'media-processing-update',
  UPDATE_CHAT: 'update-chat',
  DELETE_CHAT: 'delete-chat',
  UNFRIEND: 'unfriend',
  DELETE_CONVERSATION: 'delete-conversation',
  CONVERSATION_DELETED: 'conversation-deleted',
  MEMBER_ADDED: 'member-added',
  MEMBER_REMOVED: 'member-removed',
  NEW_NOTIFICATION: 'new-notification',
  CALL_USER: 'call-user',
  CALL_MADE: 'call-made',
  MAKE_ANSWER: 'make-answer',
  ANSWER_MADE: 'answer-made',
  CALL_REJECTED: 'call-rejected',
  HANG_UP: 'hang-up',
  ICE_CANDIDATE: 'ice-candidate',
} as const
